### ISSUE TITLE
Repository may require login

### ISSUE THREAD

**Issue by rogierlommers** [chrisruffalo/speedtrap#1]
Your docker repo is set to private

```
rlommers@macbook-rlommers [~]$ docker run -d --name speedtrap -p 8000:8000 chrisruffalo/speedtrap
Unable to find image 'chrisruffalo/speedtrap:latest' locally
docker: Error response from daemon: pull access denied for chrisruffalo/speedtrap, repository does not exist or may require 'docker login'.
```

**Comment by chrisruffalo** [comment]
@rogierlommers I initially intended with that readme that you you would need to locally build it for yourself but I went and found out that there is now a docker cloud integration with Github so it gets automatically built when new content is pushed.

Should be available now: https://hub.docker.com/r/chrisruffalo/speedtrap/

Sorry about that.
